/*
 * WhatsApp API
 * A RESTful API for a WhatsApp clone application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;

/**
 * BlockedUser
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-04-15T13:46:39.360Z")
public class BlockedUser {
  @SerializedName("id")
  private UUID id = null;

  @SerializedName("blockerId")
  private UUID blockerId = null;

  @SerializedName("blockedId")
  private UUID blockedId = null;

  @SerializedName("timestamp")
  private OffsetDateTime timestamp = null;

  public BlockedUser id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * The blocked user&#39;s UUID.
   * @return id
  **/
  @ApiModelProperty(value = "The blocked user's UUID.")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public BlockedUser blockerId(UUID blockerId) {
    this.blockerId = blockerId;
    return this;
  }

   /**
   * The UUID of the user who blocked the other user.
   * @return blockerId
  **/
  @ApiModelProperty(value = "The UUID of the user who blocked the other user.")
  public UUID getBlockerId() {
    return blockerId;
  }

  public void setBlockerId(UUID blockerId) {
    this.blockerId = blockerId;
  }

  public BlockedUser blockedId(UUID blockedId) {
    this.blockedId = blockedId;
    return this;
  }

   /**
   * The UUID of the user who was blocked.
   * @return blockedId
  **/
  @ApiModelProperty(value = "The UUID of the user who was blocked.")
  public UUID getBlockedId() {
    return blockedId;
  }

  public void setBlockedId(UUID blockedId) {
    this.blockedId = blockedId;
  }

  public BlockedUser timestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * The timestamp when the user was blocked.
   * @return timestamp
  **/
  @ApiModelProperty(value = "The timestamp when the user was blocked.")
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BlockedUser blockedUser = (BlockedUser) o;
    return Objects.equals(this.id, blockedUser.id) &&
        Objects.equals(this.blockerId, blockedUser.blockerId) &&
        Objects.equals(this.blockedId, blockedUser.blockedId) &&
        Objects.equals(this.timestamp, blockedUser.timestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, blockerId, blockedId, timestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BlockedUser {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    blockerId: ").append(toIndentedString(blockerId)).append("\n");
    sb.append("    blockedId: ").append(toIndentedString(blockedId)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

