/*
 * WhatsApp API
 * A RESTful API for a WhatsApp clone application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;

/**
 * GroupAdmin
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-04-15T13:46:39.360Z")
public class GroupAdmin {
  @SerializedName("id")
  private UUID id = null;

  @SerializedName("chatId")
  private UUID chatId = null;

  @SerializedName("userId")
  private UUID userId = null;

  @SerializedName("timestamp")
  private OffsetDateTime timestamp = null;

  public GroupAdmin id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * The group admin&#39;s UUID.
   * @return id
  **/
  @ApiModelProperty(value = "The group admin's UUID.")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public GroupAdmin chatId(UUID chatId) {
    this.chatId = chatId;
    return this;
  }

   /**
   * The UUID of the group chat.
   * @return chatId
  **/
  @ApiModelProperty(value = "The UUID of the group chat.")
  public UUID getChatId() {
    return chatId;
  }

  public void setChatId(UUID chatId) {
    this.chatId = chatId;
  }

  public GroupAdmin userId(UUID userId) {
    this.userId = userId;
    return this;
  }

   /**
   * The UUID of the user who is the group admin.
   * @return userId
  **/
  @ApiModelProperty(value = "The UUID of the user who is the group admin.")
  public UUID getUserId() {
    return userId;
  }

  public void setUserId(UUID userId) {
    this.userId = userId;
  }

  public GroupAdmin timestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * The timestamp when the user became a group admin.
   * @return timestamp
  **/
  @ApiModelProperty(value = "The timestamp when the user became a group admin.")
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GroupAdmin groupAdmin = (GroupAdmin) o;
    return Objects.equals(this.id, groupAdmin.id) &&
        Objects.equals(this.chatId, groupAdmin.chatId) &&
        Objects.equals(this.userId, groupAdmin.userId) &&
        Objects.equals(this.timestamp, groupAdmin.timestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, chatId, userId, timestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroupAdmin {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    chatId: ").append(toIndentedString(chatId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

