/*
 * WhatsApp API
 * A RESTful API for a WhatsApp clone application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;

/**
 * MessageReaction
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-04-15T13:46:39.360Z")
public class MessageReaction {
  @SerializedName("id")
  private UUID id = null;

  @SerializedName("messageId")
  private UUID messageId = null;

  @SerializedName("userId")
  private UUID userId = null;

  /**
   * The type of reaction.
   */
  @JsonAdapter(ReactionTypeEnum.Adapter.class)
  public enum ReactionTypeEnum {
    LIKE("like"),
    
    DISLIKE("dislike"),
    
    LOVE("love"),
    
    LAUGH("laugh"),
    
    SAD("sad"),
    
    ANGRY("angry"),
    
    SURPRISED("surprised");

    private String value;

    ReactionTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ReactionTypeEnum fromValue(String text) {
      for (ReactionTypeEnum b : ReactionTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<ReactionTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ReactionTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ReactionTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return ReactionTypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("reactionType")
  private ReactionTypeEnum reactionType = null;

  @SerializedName("timestamp")
  private OffsetDateTime timestamp = null;

  public MessageReaction id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * The message reaction&#39;s UUID.
   * @return id
  **/
  @ApiModelProperty(value = "The message reaction's UUID.")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public MessageReaction messageId(UUID messageId) {
    this.messageId = messageId;
    return this;
  }

   /**
   * The UUID of the message being reacted to.
   * @return messageId
  **/
  @ApiModelProperty(value = "The UUID of the message being reacted to.")
  public UUID getMessageId() {
    return messageId;
  }

  public void setMessageId(UUID messageId) {
    this.messageId = messageId;
  }

  public MessageReaction userId(UUID userId) {
    this.userId = userId;
    return this;
  }

   /**
   * The UUID of the user who reacted to the message.
   * @return userId
  **/
  @ApiModelProperty(value = "The UUID of the user who reacted to the message.")
  public UUID getUserId() {
    return userId;
  }

  public void setUserId(UUID userId) {
    this.userId = userId;
  }

  public MessageReaction reactionType(ReactionTypeEnum reactionType) {
    this.reactionType = reactionType;
    return this;
  }

   /**
   * The type of reaction.
   * @return reactionType
  **/
  @ApiModelProperty(value = "The type of reaction.")
  public ReactionTypeEnum getReactionType() {
    return reactionType;
  }

  public void setReactionType(ReactionTypeEnum reactionType) {
    this.reactionType = reactionType;
  }

  public MessageReaction timestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * The timestamp when the reaction was added.
   * @return timestamp
  **/
  @ApiModelProperty(value = "The timestamp when the reaction was added.")
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MessageReaction messageReaction = (MessageReaction) o;
    return Objects.equals(this.id, messageReaction.id) &&
        Objects.equals(this.messageId, messageReaction.messageId) &&
        Objects.equals(this.userId, messageReaction.userId) &&
        Objects.equals(this.reactionType, messageReaction.reactionType) &&
        Objects.equals(this.timestamp, messageReaction.timestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, messageId, userId, reactionType, timestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MessageReaction {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    messageId: ").append(toIndentedString(messageId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    reactionType: ").append(toIndentedString(reactionType)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

